wandb_version: 1

learning_rate:
  desc: null
  value: 0.01
architecture:
  desc: null
  value: Transformer
dataset:
  desc: null
  value: ms_sequences_with_different_probability
epochs:
  desc: null
  value: 15
_wandb:
  desc: null
  value:
    python_version: 3.12.3
    cli_version: 0.17.0
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1717691961
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 2
      - 16
      - 23
      4: 3.12.3
      5: 0.17.0
      8:
      - 1
      - 4
      - 5
      13: darwin-arm64
